# Generated by Django 3.1.2 on 2020-12-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20201215_1101'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='working_at',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
