# Generated by Django 3.1.2 on 2020-12-15 15:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20201215_1101'),
        ('contacts', '0002_auto_20201215_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_at',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
