# Generated by Django 3.1.2 on 2020-10-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20201023_1811'),
        ('contacts', '0003_auto_20201028_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='working_at',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
