# Generated by Django 3.1.2 on 2020-11-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Country', models.CharField(max_length=150)),
                ('Vat_Number', models.IntegerField()),
                ('Role', models.CharField(choices=[('CLI', 'Client'), ('PROV', 'Provider')], default=None, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
