# Generated by Django 3.1.2 on 2020-10-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.CharField(choices=[('CLI', 'Client'), ('PROV', 'Provider')], default=None, max_length=150),
        ),
    ]
