# Generated by Django 3.1.2 on 2020-10-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20201023_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='role',
        ),
    ]
