# Generated by Django 3.1.2 on 2020-10-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20201023_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='role',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='vat_number',
            new_name='Vat_Number',
        ),
    ]
