# Generated by Django 3.1.2 on 2020-10-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('contact_idd', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=150)),
            ],
        ),
    ]
