# Generated by Django 3.1.2 on 2020-10-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='contact_idd',
            new_name='contact_id',
        ),
    ]
