# Generated by Django 3.1.2 on 2020-10-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20201023_1811'),
        ('contacts', '0001_initial'),
        ('invoices', '0002_auto_20201023_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
